### ISSUE TITLE
Project config file is malformed

### ISSUE THREAD

**Issue by mptrsen** [nf-core/detaxizer#7]
### Description of the bug

Nextflow 20.10.0 complains that the config is malformed when I do not specify a config file. The .nextflow.log (see below) hints at the provided nextflow.config, but I can't spot the issue.

The sample sheet is in csv format with three columns as described in the [usage documentation](https://nf-co.re/detaxizer/usage)

Expected: normal pipeline run.

### Command used and terminal output

```console
$ nextflow run nf-core/detaxizer --input samplesheet.csv --outdir results/detaxizer

N E X T F L O W  ~  version 20.10.0
Pulling nf-core/detaxizer ...
Project config file is malformed -- Cause: No signature of method: nextflow.config.ConfigParser$_parse_closure5.id() is applicable for argument types: (String) values: [nf-validation@1.1.3]
Possible solutions: is(java.lang.Object), is(java.lang.Object), find(), find(), find(groovy.lang.Closure), find(groovy.lang.Closure)
```

### Relevant files

.nextflow.log:

```
Jan-30 15:54:32.091 [main] INFO  nextflow.cli.CmdRun - Pulling nf-core/detaxizer ...
Jan-30 15:54:32.092 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/nf-core/detaxizer/contents/nextflow.config
Jan-30 15:54:33.089 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.Exception: Project config file is malformed -- Cause: No signature of method: nextflow.config.ConfigParser$_parse_closure5.id() is applicable for argument types: (String) values: [nf-validation@1.1.3]
```

### System information

Nextflow 20.10.0
Hardware: HPC
Executor: Tried Slurm, but also get the issue locally
No container
OS: Ubuntu
There is no detaxizer version yet

**Comment by jannikseidelQBiC** [comment]
Hi and thanks for the report!
There is a major update coming to detaxizer in the next few days, which will also fix the wrong usage information (it is the default so far).
Sorry for the inconvenience and I am on it!

**Comment by d4straub** [comment]
FYI, usual required nextflow version is >=23.04.0, which is detailed in the README.md in branch dev. There isnt any release of the pipeline yet so you cannot expect a smooth experience, though.

**Comment by jannikseidelQBiC** [comment]
The update fixed the issue with the wrong usage information and you can try out the pipeline, but as mentioned be aware that it is still under development.
